version: '3.7'

services:
  #    web:
  #      build: ./app
  #      command: python manage.py runserver 0.0.0.0:8000
  #      volumes:
  #        - ./app/:/usr/src/app/
  #      ports:
  #        - 8000:8000
  #      env_file:
  #        - ./.env.dev
  #      depends_on:
  #        - db
  #        - zookeeper
  #        - kafka
  db:
    image: postgres:12.0-alpine
    container_name: pg_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - 5432:5432

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"

    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  postgres_data:
